"""initial schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    role = postgresql.ENUM("ADMIN", "TEACHER", "STUDENT", name="userrole", create_type=False)
    role.create(op.get_bind(), checkfirst=True)
    sess = postgresql.ENUM("DRAFT", "RUNNING", "COMPLETED", "CANCELLED", name="sessionstatus", create_type=False)
    sess.create(op.get_bind(), checkfirst=True)
    op.create_table("users", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("full_name", sa.String(200), nullable=False), sa.Column("password_hash", sa.String(512), nullable=False), sa.Column("role", role, nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("groups", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("name", sa.String(200), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("group_members", sa.Column("group_id", sa.UUID(), sa.ForeignKey("groups.id", ondelete="CASCADE"), primary_key=True), sa.Column("user_id", sa.UUID(), sa.ForeignKey("users.id", ondelete="CASCADE"), primary_key=True))
    op.create_table("scenarios", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("code", sa.String(100), nullable=False, unique=True), sa.Column("title", sa.String(255), nullable=False), sa.Column("category", sa.String(255), nullable=False), sa.Column("difficulty", sa.Integer(), nullable=False, server_default="1"), sa.Column("participant_role", sa.String(100), nullable=False, server_default="Заявитель"), sa.Column("incident_payload", postgresql.JSONB(), nullable=False), sa.Column("expected_state", postgresql.JSONB(), nullable=False), sa.Column("published", sa.Boolean(), nullable=False, server_default=sa.text("false")), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_by", sa.UUID(), sa.ForeignKey("users.id"), nullable=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("event_cards", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("scenario_id", sa.UUID(), sa.ForeignKey("scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("body", postgresql.JSONB(), nullable=False), sa.Column("time_limit_sec", sa.Integer(), nullable=False, server_default="120"), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("training_sessions", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("teacher_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=False), sa.Column("group_id", sa.UUID(), sa.ForeignKey("groups.id"), nullable=True), sa.Column("status", sess, nullable=False, server_default="DRAFT"), sa.Column("title", sa.String(255), nullable=False), sa.Column("scenario_ids", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("ended_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("call_sessions", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("training_session_id", sa.UUID(), sa.ForeignKey("training_sessions.id", ondelete="CASCADE"), nullable=False), sa.Column("student_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=False), sa.Column("event_card_id", sa.UUID(), sa.ForeignKey("event_cards.id"), nullable=False), sa.Column("provider", sa.String(50), nullable=False, server_default="mock"), sa.Column("status", sa.String(50), nullable=False, server_default="RINGING"), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("answered_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("metadata", postgresql.JSONB(), nullable=False, server_default="{}"))
    op.create_table("student_actions", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("call_session_id", sa.UUID(), sa.ForeignKey("call_sessions.id", ondelete="CASCADE"), nullable=False), sa.Column("action_type", sa.String(100), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("sequence_no", sa.Integer(), nullable=False))
    op.create_table("expected_actions", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("scenario_id", sa.UUID(), sa.ForeignKey("scenarios.id", ondelete="CASCADE"), nullable=False), sa.Column("action_type", sa.String(100), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.Column("required", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("weight", sa.Float(), nullable=False, server_default="1"), sa.Column("order_no", sa.Integer(), nullable=False))
    op.create_table("assessment_results", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("call_session_id", sa.UUID(), sa.ForeignKey("call_sessions.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("score", sa.Float(), nullable=False), sa.Column("max_score", sa.Float(), nullable=False), sa.Column("duration_sec", sa.Integer(), nullable=False), sa.Column("over_time", sa.Boolean(), nullable=False), sa.Column("details", postgresql.JSONB(), nullable=False), sa.Column("ai_feedback", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_table("assessment_errors", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("assessment_result_id", sa.UUID(), sa.ForeignKey("assessment_results.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(100), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("severity", sa.String(30), nullable=False), sa.Column("action_id", sa.UUID(), nullable=True))
    op.create_table("audit_logs", sa.Column("id", sa.UUID(), primary_key=True), sa.Column("user_id", sa.UUID(), sa.ForeignKey("users.id"), nullable=True), sa.Column("event_type", sa.String(100), nullable=False), sa.Column("entity_type", sa.String(100), nullable=True), sa.Column("entity_id", sa.UUID(), nullable=True), sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))

def downgrade():
    for table in ["audit_logs","assessment_errors","assessment_results","student_actions","call_sessions","expected_actions","training_sessions","event_cards","scenarios","group_members","groups","users"]:
        op.drop_table(table)
    sa.Enum(name="sessionstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="userrole").drop(op.get_bind(), checkfirst=True)
