import {Fragment,useEffect,useRef,useState} from 'react';
import {serviceLabel} from '../components/serviceLabels';
import {api} from '../api/client';import {User} from '../types';import {factLabels} from '../components/DdsComposer';
const fieldLabels:Record<string,string>={unit:'Подразделение / бригада',responsible:'Ответственный',measures:'Принятые меры',outcome:'Результат работ'};
const normalize=(data:any)=>Object.fromEntries(Object.keys(fieldLabels).map(k=>[k,String(data?.[k]||'')]));
const date=(value:string|null)=>value?new Date(value).toLocaleString('ru-RU'):'—';
const states:Record<string,string>={NEW:'Новые',ACTIVE:'В работе',COMPLETED:'Завершённые'};
const eventTitle=(e:any)=>e.payload.status||({ADDED:'Добавлена в занятие',RECEIVED:'Получена службой',COMPLETED:'Практика завершена',UPDATE_DDS:'Сведения ДДС изменены',TEXT_INPUT:'Комментарий'} as any)[e.action_type]||e.action_type;
function History({events}:{events:any[]}){return <div className="history-table-wrap"><table className="history-table"><thead><tr><th>Дата и время</th><th>Статус / действие</th><th>Комментарий</th><th>Оператор</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{date(e.occurred_at)}</td><td>{eventTitle(e)}</td><td className="preserve-text">{e.payload.comment||e.payload.text||''}{e.payload.fields&&Object.entries(e.payload.fields).map(([k,v])=><div key={k}>{fieldLabels[k]}: {String(v)||'Очищено'}</div>)}</td><td>{e.actor}</td></tr>)}</tbody></table></div>}
export function StudentWorkspace({user,onDirtyChange}:{user:User;onDirtyChange:(dirty:boolean)=>void}){
 const dialogRef=useRef<HTMLElement>(null);
 const [items,setItems]=useState<any[]>([]),[call,setCall]=useState<any>(null);
 const [tab,setTab]=useState('card'),[panel,setPanel]=useState<'history'|'status'|null>(null),[expanded,setExpanded]=useState<string[]>([]);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('ALL');
 const [status,setStatus]=useState(''),[statusComment,setStatusComment]=useState(''),[comment,setComment]=useState('');
 const [fields,setFields]=useState<Record<string,string>>(normalize({}));
 const [seconds,setSeconds]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const storageKey='dds112_card_'+user.id;
 const fieldsDirty=!!call&&JSON.stringify(fields)!==JSON.stringify(normalize(call.dds_fields));
 const dirty=!!call&&!call.completed_at&&(fieldsDirty||!!status||!!statusComment||!!comment);
 useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false)},[dirty,onDirtyChange]);
 useEffect(()=>{if(panel!=='status')return;const previous=document.activeElement as HTMLElement|null;const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setPanel(null)}if(e.key==='Tab'){const controls=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),textarea:not(:disabled)')||[]);const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',keydown);return()=>{document.removeEventListener('keydown',keydown);previous?.focus()}},[panel]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const load=async()=>setItems(await api.inbox());
 const open=(card:any)=>{setCall(card);setTab('card');setPanel(null);setFields(normalize(card.dds_fields));setStatus('');setStatusComment('');setComment('');localStorage.setItem(storageKey,card.call_id)};
 const refreshCard=async()=>{if(call){const fresh=await api.message(call.call_id);setCall(fresh);if(!fieldsDirty)setFields(normalize(fresh.dds_fields))}await load()};
 useEffect(()=>{void run(async()=>{await load();const id=localStorage.getItem(storageKey);if(id)open(await api.message(id))})},[]);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 useEffect(()=>{if(!call)return;const tick=()=>setSeconds(Math.max(0,Math.floor((Date.parse(call.completed_at||new Date().toISOString())-Date.parse(call.started_at))/1000)));tick();if(call.completed_at)return;const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[call]);
 const send=async(kind:string,payload:any)=>{await api.action(call.call_id,{action_type:kind,payload});await refreshCard()};
 const filtered=items.filter(item=>(filter==='ALL'||item.state===filter)&&[item.number,item.title,item.incident_type,item.address,item.ekp_code,item.session_title,item.service_status].join(' ').toLocaleLowerCase('ru-RU').includes(query.trim().toLocaleLowerCase('ru-RU')));
 const close=async()=>{localStorage.removeItem(storageKey);setCall(null);setPanel(null);await load()};
 const result=call?.assessment;
 const toggleExpanded=(id:string)=>setExpanded(expanded.includes(id)?expanded.filter(v=>v!==id):[...expanded,id]);
 return <section className={'dds-workspace '+(call?'incident-open':'incident-list')}>
 {error&&<div className="error" role="alert">{error}</div>}{notice&&<p className="notice" role="status">{notice}</p>}
 {!user.dds_service_key&&<p className="notice">Для новых карточек преподаватель должен назначить вам службу ДДС.</p>}
 {!call&&<><div className="incident-search"><h1>Поиск происшествий</h1><div className="search-line"><label>Номер, тип происшествия, адрес или занятие<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Введите параметры поиска"/></label><button onClick={()=>{setQuery('');setFilter('ALL')}}>Сбросить</button><button disabled={busy} onClick={()=>run(load)}>Обновить</button></div></div>
 <div className="incident-register"><div className="register-heading"><h2>Список происшествий</h2><label>Показать<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Все ({items.length})</option>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label} ({items.filter(x=>x.state===key).length})</option>)}</select></label></div>
 <div className="table-scroll"><table className="incident-table"><thead><tr><th aria-label="Подробности"></th><th>Номер</th><th>Дата</th><th>Время</th><th>Тип происшествия</th><th>Адрес</th><th>Статус службы</th><th>Карточка</th></tr></thead><tbody>{filtered.map(item=>{const id=item.session_id+item.scenario_id;return <Fragment key={id}><tr><td><button aria-label={'Сведения о '+item.number} aria-expanded={expanded.includes(id)} onClick={()=>toggleExpanded(id)}>{expanded.includes(id)?'⌃':'⌄'}</button></td><td>{item.number}</td><td>{new Date(item.available_at).toLocaleDateString('ru-RU')}</td><td>{new Date(item.available_at).toLocaleTimeString('ru-RU')}</td><td className="incident-type">{item.incident_type}</td><td>{item.address}</td><td><span className={'status-badge status-'+item.state}>{item.service_status}</span></td><td><button disabled={busy||(!item.call_id&&!!item.active_call_id)} onClick={()=>run(async()=>{open(item.call_id?await api.message(item.call_id):await api.receiveMessage(item.session_id,item.scenario_id));await load()})}>{item.state==='NEW'?'Получить':item.state==='ACTIVE'?'Продолжить':'Просмотреть'}</button></td></tr>{expanded.includes(id)&&<tr className="incident-extra"><td colSpan={8}><b>Занятие:</b> {item.session_title} · ЕКП {item.ekp_code} · {states[item.state]}{item.received_at&&' · Получена: '+date(item.received_at)}{!item.call_id&&item.active_call_id&&' · Сначала завершите активную карточку этого занятия.'}</td></tr>}</Fragment>})}</tbody></table></div>
 {!filtered.length&&<p className="empty-state">{items.length?'Происшествий по заданным параметрам не найдено.':'Нет доступных происшествий. Дождитесь запуска занятия преподавателем.'}</p>}<div className="register-footer">Найдено: {filtered.length} · Таймер начинается при получении карточки.</div></div></>}
 {call&&<><div className="incident-topline"><button disabled={busy||dirty} onClick={()=>run(close)}>← К списку</button><div><small>Сообщение системы 112</small><strong>{call.number}</strong></div><div><small>Получена службой</small><span>{date(call.started_at)}</span></div><div className="incident-top-title"><small>Занятие</small><span>{call.session_title}</span></div><div className={seconds>call.time_limit_sec?'incident-timer overtime':'incident-timer'}><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><small>норматив {call.time_limit_sec} сек{call.completed_at?' · завершено':''}</small></div></div>
 <nav className="workspace-tabs" aria-label="Разделы карточки">{[['card','Карточка 112'],['work','Обработка ДДС'],['history','История'],...(result?[['result','Результат']]:[])].map(([key,title])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{title}</button>)}<button disabled={busy||dirty} onClick={()=>run(refreshCard)}>Обновить</button></nav>
 {dirty&&<div className="notice">Есть несохранённые изменения. <button disabled={busy} onClick={()=>{setFields(normalize(call.dds_fields));setStatus('');setStatusComment('');setComment('')}}>Сбросить изменения</button></div>}
 <div hidden={tab!=='card'} className="incident-card-grid"><div className="incident-left"><section className="work-panel"><h2>Адрес происшествия</h2><p className="incident-address">{call.body.address||'Адрес не указан'}</p></section><section className="work-panel message-panel"><h2>Описание происшествия</h2><small>{date(call.started_at)} · Система 112</small><p className="preserve-text">{call.body.message||'Описание не указано'}</p></section></div>
 <div className="incident-right"><section className="work-panel"><h2 className="dark-caption">{call.body.incident_type||call.scenario}</h2><div className="incident-facts">{Object.entries(call.body.facts||{}).map(([k,v])=><span className={v?'fact-tag selected':'fact-tag'} key={k}>{factLabels[k]||k}: {v?'да':'нет'}</span>)}</div><div className="source-field"><span>Классификация ЕКП</span><b>{call.body.ekp_code||'Не указана'}</b></div><div className="source-field"><span>Признаки происшествия</span><p>{Object.values(call.body.source_features||{}).filter(Boolean).join(' · ')||'Не указаны'}</p></div></section>
 <section className="work-panel"><h2>Обработка в службе</h2><div className="source-field"><span>Ваша служба</span><b>{serviceLabel(call.service_name)}</b></div><div className="source-field"><span>Текущий статус</span><b>{call.service_status}</b></div><div className="panel-actions"><button className="primary" disabled={busy||!!call.completed_at} onClick={()=>setPanel('status')}>Изменить статус</button><button onClick={()=>setPanel('history')}>История статусов</button><button onClick={()=>setTab('work')}>Сведения ДДС</button></div></section>
 {call.norms?.length>0&&<details className="work-panel norms-panel" open><summary>Назначенные нормативы</summary>{call.norms.map((n:any)=><p key={n.status}><b>{n.status}</b>: {n.within_sec} сек от «{n.from_status}».</p>)}</details>}</div></div>
 <div hidden={tab!=='work'} className="work-tab"><section className="work-panel"><h2>Сведения о работе службы</h2><fieldset disabled={busy||!!call.completed_at}><div className="grid two">{Object.entries(fieldLabels).map(([key,label])=><label key={key}>{label}{['unit','responsible'].includes(key)?<input maxLength={200} value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>:<textarea maxLength={4000} value={fields[key]} onChange={e=>setFields({...fields,[key]:e.target.value})}/>}</label>)}</div>{!call.completed_at&&<button className="primary" disabled={!fieldsDirty} onClick={()=>run(async()=>{const patch=Object.fromEntries(Object.entries(fields).filter(([key,value])=>value!==normalize(call.dds_fields)[key]));await send('UPDATE_DDS',{fields:patch});setNotice('Сведения ДДС сохранены.')})}>Сохранить сведения ДДС</button>}</fieldset></section>
 {!call.completed_at&&<section className="work-panel"><h2>Комментарий диспетчера</h2><fieldset disabled={busy}><label>Новая запись<textarea maxLength={4000} value={comment} onChange={e=>setComment(e.target.value)}/></label><button disabled={!comment.trim()} onClick={()=>run(async()=>{await send('TEXT_INPUT',{text:comment.trim()});setComment('');setNotice('Комментарий добавлен.')})}>Добавить комментарий</button></fieldset></section>}</div>
 <section hidden={tab!=='history'} className="work-panel"><h2>История обработки · {serviceLabel(call.service_name)}</h2><History events={call.timeline}/></section>
 {result&&<section hidden={tab!=='result'} className="work-panel"><h2>Результат практики</h2><div className="score">{result.score} / {result.max_score}</div><p>Время: {result.duration_sec} сек · общий норматив превышен: {result.over_time?'да':'нет'}</p>{result.details.criteria?.map((c:any,i:number)=><p key={i}><b>{c.label}: {c.score} / {c.max_score}</b>{c.elapsed_sec!==undefined&&<> · {c.elapsed_sec??'нет события'} сек / норматив {c.limit_sec??'без срока'}</>}</p>)}{result.details.errors.length?result.details.errors.map((e:any,i:number)=><p className="error" key={i}>{e.message}</p>):<p>Ошибок нет.</p>}<p>Проверка комментария (учебная): {result.ai_feedback.grammar_issues?.join('; ')||'Замечаний не найдено.'}</p></section>}
 <div className="service-dock"><span className="dock-caption">Службы:</span><div className="service-recipients">{(call.body.recipients||[]).map((r:any)=>{const own=r.name===call.service_name;return own?<button key={r.key} className="service-tile own-service" aria-expanded={panel==='history'} onClick={()=>setPanel(panel==='history'?null:'history')}><b>{serviceLabel(r.name)}</b><small>{call.service_status} ⌃</small></button>:<div className="service-tile" key={r.key}><b>{serviceLabel(r.name)}</b><small>Получатель карточки</small></div>})}</div>{!call.completed_at?<button className="finish-practice" disabled={busy||dirty} onClick={()=>run(async()=>{await api.complete(call.call_id);await refreshCard();setTab('result');setPanel(null);setNotice('Практика завершена.')})}>Завершить практику</button>:<span className="dock-completed">Практика завершена</span>}</div>
 {panel==='history'&&<section className="history-drawer" role="dialog" aria-label="История службы"><div className="drawer-heading"><b>{serviceLabel(call.service_name)} · история</b><button aria-label="Закрыть историю" onClick={()=>setPanel(null)}>×</button></div><History events={call.timeline}/><button disabled={busy||!!call.completed_at} onClick={()=>setPanel('status')}>✎ Изменить статус</button></section>}
 {panel==='status'&&<div className="dialog-backdrop"><section ref={dialogRef} className="status-dialog" role="dialog" aria-modal="true" aria-label="Изменить статус службы"><div className="drawer-heading"><h2>Изменить статус · {serviceLabel(call.service_name)}</h2><button aria-label="Закрыть изменение статуса" onClick={()=>setPanel(null)}>×</button></div><p>Текущий статус: <b>{call.service_status}</b></p><fieldset disabled={busy}><label>Новый статус<select autoFocus value={status} onChange={e=>setStatus(e.target.value)}><option value="">Выберите статус</option>{call.allowed_statuses.map((v:string)=><option key={v}>{v}</option>)}</select></label><label>Комментарий к статусу<textarea maxLength={4000} value={statusComment} onChange={e=>setStatusComment(e.target.value)}/></label><button className="primary" disabled={!status} onClick={()=>run(async()=>{await send('SELECT_STATUS',{status,comment:statusComment.trim()});setStatus('');setStatusComment('');setPanel('history');setNotice('Статус записан в историю.')})}>Зафиксировать статус</button></fieldset></section></div>}
 </>}
 </section>
}
